"""Rewrite the two generated blocks inside `build/installer/assoc.nsh`.

ONE PROGID PER EXTENSION (owner pick, 2026-09-01). A ProgID carries exactly one
DefaultIcon and an .ico carries one baked label, so a class shared by many
extensions prints one of their names on all of them: `prism-code.ico` said PY on
130 extensions, `prism-image.ico` said JPG on 52. One class each is the only
arrangement in which the band tells the truth.

Generated rather than hand-edited because it is now ~300 of each line and the
uninstall half has to match the install half exactly - which is the half that
has rotted before, once by 96 extensions. `fileAssoc.test.ts` checks the result
from the other side.

The blocks are SPLICED, not the file rewritten: everything outside the two
markers - the header explaining why Prism never takes a default, the macro
definitions, the Capabilities keys - is hand-written prose that a generator has
no business touching.

    python gen_assoc.py
"""
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from extmap import kinds  # noqa: E402
from langs import EXTS as LANG_EXTS  # noqa: E402

NSH = pathlib.Path(__file__).resolve().parents[2] / "build" / "installer" / "assoc.nsh"

# What Windows shows as the type's name in Explorer's Type column. One per KIND
# rather than one per extension: "Python source" is worth saying, "PY file" is
# what Windows already says on its own.
DESC = {
    "image": "Image", "video": "Video", "audio": "Audio", "document": "Document",
    "archive": "Archive", "comic": "Comic book", "code": "Text file",
}
# Where a language mark exists, the description says so.
LANG_DESC = {
    "react": "React component", "vue": "Vue component", "python": "Python source",
    "config": "Configuration", "html": "Web page", "css": "Stylesheet",
    "shell": "Script", "data": "Data file", "sql": "SQL script",
    "java": "JVM source", "swift": "Swift source", "ruby": "Ruby source",
    "prose": "Text file",
}

BEGIN_REG = "  ; ---- GENERATED by tools/icons/gen_assoc.py, do not hand-edit ----\n"
END_REG = "  ; ---- end generated ----\n"


def progid(ext):
    """`Prism.Png`, `Prism.Tar_gz`. Stable, and unique per extension."""
    return "Prism." + ext.capitalize()


def describe(ext, kind):
    return LANG_DESC.get(LANG_EXTS.get(ext), DESC[kind])


def blocks():
    table = kinds()
    exts = sorted(table)
    reg, unreg = [], []
    for e in exts:
        reg.append(f'  !insertmacro PRISM_PROGID "{progid(e)}" "{describe(e, table[e])}" "{e}"\n')
    reg.append("\n")
    for e in exts:
        reg.append(f'  !insertmacro PRISM_EXT "{e}" "{progid(e)}"\n')
    for e in exts:
        unreg.append(f'  DeleteRegKey SHELL_CONTEXT "Software\\Classes\\{progid(e)}"\n')
    unreg.append("\n")
    for e in exts:
        unreg.append(f'  !insertmacro PRISM_UNEXT "{e}" "{progid(e)}"\n')
    return "".join(reg), "".join(unreg), len(exts)


def span(text, macro, first_pat, last_pat):
    """The half-open range of PER-EXTENSION lines inside one macro.

    Bounded by the first and last generated line rather than by the macro's own
    braces, because both macros have hand-written HEAD and TAIL that a generator
    must not touch - the uninstall half ends with the Explorer verb's keys and
    the SHChangeNotify that makes Explorer notice, and a splice that ran to
    `!macroend` silently ate them. The unit tests caught it; the point of doing
    it this way is that they should not have to.
    """
    nl = chr(10)
    start = text.index("!macro " + macro + nl)
    end = text.index("!macroend", start)
    a = text.index(first_pat, start, end)
    a = text.rindex(nl, start, a) + 1
    b = text.rindex(last_pat, a, end)
    b = text.index(nl, b) + 1
    return a, b


def splice(text, macro, body, first_pat, last_pat):
    a, b = span(text, macro, first_pat, last_pat)
    return text[:a] + BEGIN_REG + body + END_REG + text[b:]


def main():
    t = NSH.read_text(encoding="utf-8")
    reg, unreg, n = blocks()
    t = splice(t, "PRISM_REGISTER_TYPES", reg,
               "!insertmacro PRISM_PROGID", "!insertmacro PRISM_EXT ")
    t = splice(t, "PRISM_UNREGISTER_TYPES", unreg,
               'DeleteRegKey SHELL_CONTEXT "Software\\Classes\\Prism.',
               "!insertmacro PRISM_UNEXT ")
    NSH.write_text(t, encoding="utf-8")
    defined = len(set(re.findall(r'PRISM_PROGID\s+"([^"]+)"', t)))
    print(f"{n} extensions, {defined} ProgIDs defined")


if __name__ == "__main__":
    main()
